include:
  - remote: 'https://gitlab.cern.ch/c2mon/c2mon/-/raw/master/.gitlab-ci-templates/internal-gitlab-ci.yml'

# Get the settings file from c2mon project
before_script:
  - curl -O https://gitlab.cern.ch/c2mon/c2mon/raw/master/settings.xml
