image: gitlab-registry.cern.ch/industrial-controls/sw-infra/jenkins/mvn-plus-jdk

stages:
  - build
  - deploy 
  - release
  - sonar

# Get the settings file from c2mon project
before_script:
  - wget https://gitlab.cern.ch/c2mon/c2mon/raw/master/settings.xml

# Fully build and publish master branch
build_and_publish:
  type: deploy
  script: 
    - mvn -B deploy -Djavax.net.ssl.trustStore=${CACERTS} --settings settings.xml
  only:
    - master
  except:
    - tags
    
# Just run tests on feature branches
build:
  type: build
  script:
    - mvn -B test -Djavax.net.ssl.trustStore=${CACERTS} --settings settings.xml
  except:
    - master
    - tags
    
sonar_preview:
  type: sonar
  script:
    - mvn -B compile sonar:sonar -Dmaven.test.skip=true -Djavax.net.ssl.trustStore=${CACERTS} -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.max_major_issues_gate=0 --settings settings.xml
  except:
    - master
    - tags

quality_assurance:
  stage: sonar
  script:
    - mvn package sonar:sonar -Dmaven.test.skip=true -Djavax.net.ssl.trustStore=${CACERTS} -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml --settings settings.xml
  only:
    - master
  except:
    - tags
